version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean package -Pprod
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/hero-ms.jar
  discard-paths: yes
